baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TablePie'
# https://themes.gohugo.io/themes/typo/
theme = 'Typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxxx"

ignorefiles=["4 ARCHIVE/Templates/*", "5 INBOX/notes/_footer.md"]

[params]
# Appearance
theme = 'auto'

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = '我们都只是这颗蓝色星球上的微小尘埃。'
homeIntroContent = """
所以别计较太多，好好生活。
![](https://pic-simon.oss-cn-shenzhen.aliyuncs.com/PIA10120~orig.jpg)
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100
# Display summaries under post list entries
listSummaries = false
# List entries date format
listDateFormat = '2006 Jan 2'

[params.breadcrumbs]
enabled = false

# Social icons
[[params.social]]
name = "twitter"
url = "https://x.com/LBZZYZ"

[[params.social]]
name = "bilibili"
url = "https://space.bilibili.com/63960087?spm_id_from=333.1007.0.0"

[[params.social]]
name = "github"
url = "https://github.com/LBZZYZ"

# Main menu pages
[[params.menu]]
name = "技术"
url = "/tags/tech"

[[params.menu]]
name = "归档"
url = "/posts"

# Syntax highlight on code blocks, all styles: 
# https://xyproto.github.io/splash/docs/all.html
# I suggest algol
[markup]
[markup.highlight]
style = 'algol'
